---
ActiveText:
  NightSky: '#8080FF'
  Desert: '#1C5E75'
  Dusk: '#70EBDE'
  Win10: '#8080FF'
  Win10White: '#00009F'
ButtonBorder:
  NightSky: '#FFFFFF'
  Desert: '#C0C0C0'
  Dusk: '#FFFFFF'
  Win10: '#FFFFFF'
  Win10White: '#C0C0C0'
ButtonFace:
  NightSky: '#000000'
  Desert: '#FFFAEF'
  Dusk: '#2D3236'
  Win10: '#000000'
  Win10White: '#FFFFFF'
ButtonText:
  NightSky: '#FFEE32'
  Desert: '#202020'
  Dusk: '#B6F6F0'
  Win10: '#FFFFFF'
  Win10White: '#000000'
Canvas:
  NightSky: '#000000'
  Desert: '#FFFAEF'
  Dusk: '#2D3236'
  Win10: '#000000'
  Win10White: '#FFFFFF'
CanvasText:
  NightSky: '#FFFFFF'
  Desert: '#3D3D3D'
  Dusk: '#FFFFFF'
  Win10: '#FFFF00'
  Win10White: '#000000'
Field:
  NightSky: '#000000'
  Desert: '#FFFAEF'
  Dusk: '#2D3236'
  Win10: '#000000'
  Win10White: '#FFFFFF'
FieldText:
  NightSky: '#FFFFFF'
  Desert: '#3D3D3D'
  Dusk: '#FFFFFF'
  Win10: '#FFFF00'
  Win10White: '#000000'
GrayText:
  NightSky: '#A6A6A6'
  Desert: '#676767'
  Dusk: '#A6A6A6'
  Win10: '#00FF00'
  Win10White: '#600000'
Highlight:
  NightSky: '#D6B4FD'
  Desert: '#903909'
  Dusk: '#A1BFDE'
  Win10: '#008000'
  Win10White: '#37006E'
HighlightText:
  NightSky: '#2B2B2B'
  Desert: '#FFF5E3'
  Dusk: '#212D3B'
  Win10: '#FFFFFF'
  Win10White: '#FFFFFF'
LinkText:
  NightSky: '#8080FF'
  Desert: '#1C5E75'
  Dusk: '#70EBDE'
  Win10: '#8080FF'
  Win10White: '#00009F'
Mark:
  NightSky: '#FFFF00'
  Desert: '#FFFF00'
  Dusk: '#FFFF00'
  Win10: '#FFFF00'
  Win10White: '#FFFF00'
MarkText:
  NightSky: '#000000'
  Desert: '#000000'
  Dusk: '#000000'
  Win10: '#000000'
  Win10White: '#000000'
SelectedItem:
  NightSky: '#D6B4FD'
  Desert: '#903909'
  Dusk: '#A1BFDE'
  Win10: '#008000'
  Win10White: '#37006E'
SelectedItemText:
  NightSky: '#2B2B2B'
  Desert: '#FFF5E3'
  Dusk: '#212D3B'
  Win10: '#FFFFFF'
  Win10White: '#FFFFFF'
AccentColor:
  NightSky: '#D6B4FD'
  Desert: '#903909'
  Dusk: '#A1BFDE'
  Win10: '#008000'
  Win10White: '#37006E'
AccentColorText:
  NightSky: '#000000'
  Desert: '#FFFFFF'
  Dusk: '#000000'
  Win10: '#FFFFFF'
  Win10White: '#FFFFFF'
VisitedText:
  NightSky: '#80FF80'
  Desert: '#9E3D96'
  Dusk: '#96FF9B'
  Win10: '#80FF00'
  Win10White: '#800080'
