---
badge/background/color:
  Light: 'transparent'
  Dark: 'transparent'
  HCM: '{HCM Theme$Canvas}'
badge/border/color:
  Light: 'rgba(21, 20, 26, 0.40)'
  Dark: 'rgba(251, 251, 254, 0.40)'
  HCM: '{HCM Theme$CanvasText}'
badge/filled/background/color:
  Light: '{Colors$color/green/70}'
  Dark: '{Colors$color/green/40}'
  HCM: '{HCM Theme$AccentColor}'
badge/filled/border/color:
  Light: 'rgba(251, 251, 254, 0.40)'
  Dark: 'rgba(21, 20, 26, 0.40)'
  HCM: '{HCM Theme$CanvasText}'

border/color/overlay:
  Light: '#F0F0F4'
  Dark: '#52525E'
  HCM: '{HCM Theme$CanvasText}'
border/color/default:
  Light: '#CFCFD8'
  Dark: '#3A3944'
  HCM: '{HCM Theme$CanvasText}'

background/color/tabstrip:
  Light: 'F0F0F4'
  Dark: '1C1B22'
  HCM: '{HCM Theme$ActiveText}'
background/color/toolbar:
  Light: '#F9F9FB'
  Dark: '#2B2A33'
  HCM: '{HCM Theme$Canvas}'
background/color/canvas-v2:
  Light: '#F9F9FB'
  Dark: '#1C1B22'
  HCM: '{HCM Theme$Canvas}'
background/color/panel:
  Light: '{Theme$background/color/box}'
  Dark: '#42414D'
  HCM: '{Theme$background/color/box}'
background/color/backdrop:
  Light: 'rgba(0, 0, 0, 0.25)'
  Dark: 'rgba(0, 0, 0, 0.25)'
  HCM: 'rgba(0, 0, 0, 0.25)'

color/accent/primary/deemphasized:
  Light: 'rgba(0, 98, 250, 0.08)'
  Dark: 'rgba(0, 202, 219, 0.08)'
  HCM: '{HCM Theme$SelectedItem}'

promo/background/color:
  Light: 'rgba(21, 20, 26, 0.04)'
  Dark: 'rgba(251, 251, 254, 0.04)'
  HCM: '{HCM Theme$Canvas}'
promo/border/color:
  Light: 'rgba(21, 20, 26, 0.12)'
  Dark: 'rgba(251, 251, 254, 0.12)'
  HCM: '{HCM Theme$CanvasText}'
### Tabs
# Background
tab/background/color:
  Light: '{Theme$button/background/color/ghost}'
  Dark: '{Theme$button/background/color/ghost}'
  HCM: 'transparent'
tab/background/color/hover:
  Light: '{Theme$button/background/color/hover}'
  Dark: '{Theme$button/background/color/hover}'
  HCM: 'transparent'
tab/background/color/active:
  Light: '{Colors$color/white}'
  Dark: '#52525E'
  HCM: '{HCM Theme$ButtonFace}'
tab/background/color/pinned:
  Light: '{Theme$button/background/color}'
  Dark: '{Theme$button/background/color}'
  HCM: 'transparent'
# Border
tab/border/color:
  Light: 'transparent'
  Dark: 'transparent'
  HCM: '{HCM Theme$ButtonText}'
tab/border/color/hover:
  Light: 'transparent'
  Dark: 'transparent'
  HCM: '{HCM Theme$SelectedItem}'
tab/border/color/active:
  Light: 'transparent'
  Dark: 'transparent'
  HCM: '{HCM Theme$SelectedItem}'
# Text
tab/text/color:
  Light: '{Theme$text/color}'
  Dark: '{Theme$text/color}'
  HCM: '{HCM Theme$AccentColorText}'
tab/text/color/deemphasized:
  Light: '{Theme$text/color/deemphasized}'
  Dark: '{Theme$text/color/deemphasized}'
  HCM: '{HCM Theme$AccentColorText}'
tab/text/color/hover:
  Light: '{Theme$text/color}'
  Dark: '{Theme$text/color}'
  HCM: '{HCM Theme$AccentColorText}'
tab/text/color/deemphasized/hover:
  Light: '{Theme$text/color/deemphasized}'
  Dark: '{Theme$text/color/deemphasized}'
  HCM: '{HCM Theme$AccentColorText}'
tab/text/color/active:
  Light: '{Theme$text/color}'
  Dark: '{Theme$text/color}'
  HCM: '{HCM Theme$CanvasText}'
tab/text/color/deemphasized/active:
  Light: '{Theme$text/color/deemphasized}'
  Dark: '{Theme$text/color/deemphasized}'
  HCM: '{HCM Theme$CanvasText}'
