name: 'Central>Figma Variable Import'
description: 'Imports variables from Mozilla central to Figma'

inputs:
  FIGMA_URL_DESKTOP_STYLES_DESKTOP_STYLES:
    description: 'URL of the Figma file for desktop styles'
  FIGMA_URL_DESKTOP_STYLES_FIREFOX_COLORS:
    description: 'URL of the Figma file for Firefox colors'
  FIGMA_ACCESS_TOKEN:
    description: 'Access token to authenticate with Figma'
    required: true
  SLACK_WEBHOOK_SUCCESS:
    description: 'Webhook URL of a Slack workflow to notify on success'
  SLACK_WEBHOOK_FAILURE:
    description: 'Webhook URL of a Slack workflow to notify on failure'
  ONLY_RUN_JOBS:
    description: 'Comma-separated list of jobs to run. If not set, all jobs will be run'
  DRY_RUN:
    description: 'Whether to run the action without making changes'
    default: 'true'

runs:
  using: 'node20'
  main: 'index.js'
