name: 'Variable Import Check (apply to file)'

on:
  workflow_dispatch:
    inputs:
      figmaUrl:
        type: 'string'
        description: 'URL of the branch to import and update variables'
        required: true

jobs:
  checks:
    runs-on: 'ubuntu-latest'
    environment: 'Actions'
    name: 'Check if there are potential updates to the Figma Desktop Styles'
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Install dependencies
        run: npm ci --production
      - name: Check for updates and apply them
        uses: './dist'
        with:
          FIGMA_URL: '${{ github.event.inputs.figmaUrl }}'
          FIGMA_ACCESS_TOKEN: '${{ secrets.FIGMA_ACCESS_TOKEN }}'
          SLACK_WEBHOOK_FAILURE: '${{ secrets.SLACK_WEBHOOK_FAILURE }}'
          DRY_RUN: 'false'
