name: 'Update Android M3 modes'

on:
  workflow_dispatch:
    inputs:
      figmaUrl:
        type: 'string'
        description: '"Android Components" branch or file URL'
        required: true
      dryRun:
        type: 'boolean'
        description: 'Do not apply changes'
        default: false

jobs:
  checks:
    runs-on: 'ubuntu-latest'
    environment: 'Actions'
    name: 'Run figma variable script'
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Install dependencies
        run: npm ci --production
      - name: 'Run ANDROID_M3_MODES job'
        uses: './dist'
        with:
          FIGMA_URL_ANDROID_COMPONENTS: '${{ github.event.inputs.figmaUrl }}'
          FIGMA_URL_MOBILE_STYLES: '${{ secrets.FIGMA_URL_MOBILE_STYLES }}'
          FIGMA_ACCESS_TOKEN: '${{ secrets.FIGMA_ACCESS_TOKEN }}'
          SLACK_WEBHOOK_FAILURE: '${{ secrets.SLACK_WEBHOOK_FAILURE }}'
          ONLY_RUN_JOBS: 'ANDROID_M3_MODES'
          DRY_RUN: '${{ github.event.inputs.dryRun }}'
