name: 'Sync tokens to Nova Styles'

on:
  workflow_dispatch:
    inputs:
      figmaUrl:
        type: 'string'
        description: '"Nova Styles" branch or file URL'
        required: true
      dryRun:
        type: 'boolean'
        description: 'Do not apply changes'
        default: false

jobs:
  checks:
    runs-on: 'ubuntu-latest'
    environment: 'Actions'
    name: 'Run figma variable script'
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: 'Run NOVA_STYLES job'
        uses: './'
        with:
          FIGMA_URL_EXPERIMENTAL_DESKTOP_STYLES: '${{ github.event.inputs.figmaUrl }}'
          FIGMA_ACCESS_TOKEN: '${{ secrets.FIGMA_ACCESS_TOKEN }}'
          SLACK_WEBHOOK_FAILURE: '${{ secrets.SLACK_WEBHOOK_FAILURE }}'
          ONLY_RUN_JOBS: 'NOVA_STYLES'
          DRY_RUN: '${{ github.event.inputs.dryRun }}'
